INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/lib/include)
SET(INCLUDE ${CMAKE_SOURCE_DIR}/include)
FILE(GLOB SOURCE "*.cpp")
LIST(REMOVE_ITEM SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)
ADD_LIBRARY(hello ${SOURCE})
TARGET_INCLUDE_DIRECTORIES(hello PUBLIC "${INCLUDE}")
ADD_EXECUTABLE(helloExe ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)
TARGET_LINK_LIBRARIES(helloExe hello funclib)